### ISSUE TITLE
Trigger chaos experiments via Keptn

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/litmus-service#2]
Action items

- [x] Install instructions for Keptn
- [x] Install instructions for Litmus
- [x] Setup instructions for demo application
- [x] Setup instruction for chaos trigger
- [x] Implement the DeploymentFinished event handler to trigger chaos 
- [x] Implement the TestFinished event handler to stop chaos
- [x] Write documentation
- [x] Write tutorial
- [x] Joint webinar / community meeting
- [x] Joint blog post

**Comment by jetzlstorfer** [comment]
Right now jmeter-service as well as the litmus-service send a `test-finished` event that triggers the evaluation in Keptn. 
Clarification needed how to deal with this in Keptn 0.7.x (in Keptn 0.8.x there will be improvements for this).

**Comment by jetzlstorfer** [comment]
Cleanup of the experiment is throwing errors.
```
2020-10-01T12:20:45.264698332Z 2020/10/01 12:20:45 Deleting chaos experiment resources
2020-10-01T12:20:45.352877445Z 2020/10/01 12:20:45 Error execute kubectl delete command: Error executing command kubectl delete -f litmus/experiment.yaml: exit status 1
2020-10-01T12:20:45.352914192Z Error from server (NotFound): error when deleting "litmus/experiment.yaml": chaosengines.litmuschaos.io "carts-chaos" not found
```

We need to investigate why the error is thrown and fix it

**Comment by jetzlstorfer** [comment]
Correct return code has to be sent from the Litmus-Service to the Keptn control plane. Right now it is always "pass".

**Comment by jetzlstorfer** [comment]
Include the Chaos Experiment Result in the actual result that is sent to Keptn.

**Comment by ksatchit** [comment]
The latest release (0.2.0) of the service works with Keptn 0.8.0

The checklist defined as part of this issue has been completed with the addition of the [tutorial](https://tutorials.keptn.sh/tutorials/keptn-litmus-08/index.html?index=..%2F..index#0) & blog posts ([part-1](https://medium.com/keptn/evaluating-kubernetes-resiliency-with-keptn-and-litmuschaos-66bdfb35cbdd) & [part-2](https://medium.com/keptn/part-2-evaluating-application-resiliency-with-keptn-and-litmuschaos-use-case-and-demo-f43b264a2294))
