### ISSUE TITLE
Include the Chaos Experiment Result in the actual result that is sent to Keptn.

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/litmus-service#7]
Related to #6 

Since litmus also collects data for each chaos experiment run, we should include this when sending the results back to Keptn.

**Comment by ksatchit** [comment]
This is [being performed](https://github.com/keptn-sandbox/litmus-service/blob/15a2c8033f4c62e9dac8407197403ec1e0818bd3/eventhandlers.go#L158) as part of release [0.2.0](https://github.com/keptn-sandbox/litmus-service/releases/tag/0.2.0).
